name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC-2022",
            os: windows-latest,
            artifact: "windows_msvc2022.7z",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 17 2022"
          }


    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          vsversion: 2022

      # Get CMake, see https://github.com/marketplace/actions/get-cmake
      - name: get-cmake
        uses: lukka/get-cmake@v3.24.3
      
      #Now go to using: https://github.com/marketplace/actions/run-cmake      
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "Building branch ${{ github.ref }} of repository ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  
    
      - name: Build dependencies on windows
        shell: cmd
        if: runner.os == 'Windows'
        working-directory: ${{runner.workspace}}
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          cmake --version
          cl.exe


      - run: echo "Job status is ${{ job.status }}."



